### ISSUE TITLE
Keeps crashing on the latest version of QuickLook

### ISSUE THREAD

**Issue by dyphire** [emako/QuickLook.Plugin.MarkmapViewer#2]
https://github.com/QL-Win/QuickLook/releases/tag/latest

This plugin when used with the latest version of QuickLook previews markdown files fine only the first time it is opened, and causes a crash when the preview window is opened again. After removing this plugin, it returns to normal.

**Comment by emako** [comment]
It should be caused by the inconsistent versions of WebView2 and HtmlViewer

I fix it later

**Comment by emako** [comment]
https://github.com/emako/QuickLook.Plugin.MarkmapViewer/releases
